import { Product } from "./types";

export const products: Product[] = [
  {
    id: 1,
    title: "iPhone 14 Pro",
    category: "Mobile",
    brand: "Apple",
    image: "https://via.placeholder.com/150",
    description: "The latest flagship smartphone from Apple, featuring an advanced camera system and powerful performance.",
    price: 999,
  },
  {
    id: 2,
    title: "Galaxy S22",
    category: "Mobile",
    brand: "Samsung",
    image: "https://via.placeholder.com/150",
    description: "Samsung's flagship smartphone with a stunning display and innovative features.",
    price: 999,
  },
  {
    id: 3,
    title: "Pixel 6",
    category: "Mobile",
    brand: "Google",
    image: "https://via.placeholder.com/150",
    description: "Google's Pixel 6 offers a pure Android experience with excellent camera capabilities.",
    price: 999,
  },
  {
    id: 4,
    title: "Xperia 5 III",
    category: "Mobile",
    brand: "Sony",
    image: "https://via.placeholder.com/150",
    description: "Sony's compact yet powerful smartphone with high-quality audio and video features.",
    price: 999,
  },
  {
    id: 5,
    title: "Moto G Power",
    category: "Mobile",
    brand: "Motorola",
    image: "https://via.placeholder.com/150",
    description: "Motorola's Moto G Power combines long battery life with reliable performance.",
    price: 999,
  },
  {
    id: 6,
    title: "Redmi Note 11",
    category: "Mobile",
    brand: "Xiaomi",
    image: "https://via.placeholder.com/150",
    description: "Xiaomi's Redmi Note 11 offers great value for money with impressive features.",
    price: 999,
  },
  {
    id: 7,
    title: "OnePlus 9 Pro",
    category: "Mobile",
    brand: "OnePlus",
    image: "https://via.placeholder.com/150",
    description: "OnePlus 9 Pro delivers fast performance and a smooth user experience.",
    price: 999,
  },
  {
    id: 8,
    title: "Asus ROG Phone 5",
    category: "Mobile",
    brand: "Asus",
    image: "https://via.placeholder.com/150",
    description: "Asus ROG Phone 5 is designed for mobile gaming enthusiasts with powerful hardware.",
    price: 999,
  },
  {
    id: 9,
    title: "Nokia XR20",
    category: "Mobile",
    brand: "Nokia",
    image: "https://via.placeholder.com/150",
    description: "Nokia XR20 is a rugged smartphone built to withstand tough conditions.",
    price: 999,
  },
  {
    id: 10,
    title: "LG Velvet",
    category: "Mobile",
    brand: "LG",
    image: "https://via.placeholder.com/150",
    description: "LG Velvet combines elegant design with a premium display and camera system.",
    price: 999,
  },
  {
    id: 11,
    title: "iPad Pro",
    category: "Tablet",
    brand: "Apple",
    image: "https://via.placeholder.com/150",
    description: "iPad Pro offers desktop-class performance and versatility in a sleek and portable design.",
    price: 999,
  },
  {
    id: 12,
    title: "Galaxy Tab S8",
    category: "Tablet",
    brand: "Samsung",
    image: "https://via.placeholder.com/150",
    description: "Samsung Galaxy Tab S8 features a stunning display and powerful performance for productivity and entertainment.",
    price: 999,
  },
  {
    id: 13,
    title: "Surface Pro 8",
    category: "Tablet",
    brand: "Microsoft",
    image: "https://via.placeholder.com/150",
    description: "Microsoft Surface Pro 8 is a versatile 2-in-1 device with powerful performance and productivity features.",
    price: 999,
  },
  {
    id: 14,
    title: "Fire HD 10",
    category: "Tablet",
    brand: "Amazon",
    image: "https://via.placeholder.com/150",
    description: "Amazon Fire HD 10 offers a large display and long battery life for entertainment on the go.",
    price: 999,
  },
  {
    id: 15,
    title: "Tab P11 Pro",
    category: "Tablet",
    brand: "Lenovo",
    image: "https://via.placeholder.com/150",
    description: "Lenovo Tab P11 Pro is a premium tablet with a stunning display and powerful performance for work and play.",
    price: 999,
  },
  {
    id: 16,
    title: "iPad Air",
    category: "Tablet",
    brand: "Apple",
    image: "https://via.placeholder.com/150",
    description: "iPad Air combines power and portability with a sleek design and advanced features.",
    price: 999,
  },
  {
    id: 17,
    title: "MatePad Pro",
    category: "Tablet",
    brand: "Huawei",
    image: "https://via.placeholder.com/150",
    description: "Huawei MatePad Pro offers a premium tablet experience with a large display and powerful performance.",
    price: 999,
  },
  {
    id: 18,
    title: "Yoga Tab 13",
    category: "Tablet",
    brand: "Lenovo",
    image: "https://via.placeholder.com/150",
    description: "Lenovo Yoga Tab 13 features a unique design with a built-in kickstand and powerful multimedia capabilities.",
    price: 999,
  },
  {
    id: 19,
    title: "Galaxy Tab A8",
    category: "Tablet",
    brand: "Samsung",
    image: "https://via.placeholder.com/150",
    description: "Samsung Galaxy Tab A8 offers an affordable yet feature-packed tablet experience for everyday use.",
    price: 999,
  },
  {
    id: 20,
    title: "Xperia Z4 Tablet",
    category: "Tablet",
    brand: "Sony",
    image: "https://via.placeholder.com/150",
    description: "Sony Xperia Z4 Tablet is a slim and lightweight device with a vibrant display and waterproof design.",
    price: 999,
  },
  {
    id: 21,
    title: "MacBook Pro",
    category: "Laptop",
    brand: "Apple",
    image: "https://via.placeholder.com/150",
    description: "Apple MacBook Pro delivers powerful performance and a stunning Retina display for professionals.",
    price: 999,
  },
  {
    id: 22,
    title: "Dell XPS 13",
    category: "Laptop",
    brand: "Dell",
    image: "https://via.placeholder.com/150",
    description: "Dell XPS 13 is a compact and powerful laptop with a virtually borderless InfinityEdge display.",
    price: 999,
  },
  {
    id: 23,
    title: "ThinkPad X1 Carbon",
    category: "Laptop",
    brand: "Lenovo",
    image: "https://via.placeholder.com/150",
    description: "Lenovo ThinkPad X1 Carbon is a premium business laptop with a durable yet lightweight design.",
    price: 999,
  },
  {
    id: 24,
    title: "Surface Laptop 4",
    category: "Laptop",
    brand: "Microsoft",
    image: "https://via.placeholder.com/150",
    description: "Microsoft Surface Laptop 4 offers a sleek and lightweight design with powerful performance for productivity.",
    price: 999,
  },
  {
    id: 25,
    title: "ROG Zephyrus G14",
    category: "Laptop",
    brand: "Asus",
    image: "https://via.placeholder.com/150",
    description: "Asus ROG Zephyrus G14 is a gaming laptop with a powerful AMD Ryzen processor and Nvidia GeForce graphics.",
    price: 999,
  },
  {
    id: 26,
    title: "Razer Blade 15",
    category: "Laptop",
    brand: "Razer",
    image: "https://via.placeholder.com/150",
    description: "Razer Blade 15 is a premium gaming laptop with a sleek design and high-performance components.",
    price: 999,
  },
  {
    id: 27,
    title: "MacBook Air",
    category: "Laptop",
    brand: "Apple",
    image: "https://via.placeholder.com/150",
    description: "Apple MacBook Air is an ultra-thin and lightweight laptop with all-day battery life and a stunning Retina display.",
    price: 999,
  },
  {
    id: 28,
    title: "HP Spectre x360",
    category: "Laptop",
    brand: "HP",
    image: "https://via.placeholder.com/150",
    description: "HP Spectre x360 is a versatile convertible laptop with a stylish design and long battery life.",
    price: 999,
  },
  {
    id: 29,
    title: "Acer Swift 3",
    category: "Laptop",
    brand: "Acer",
    image: "https://via.placeholder.com/150",
    description: "Acer Swift 3 is a thin and light laptop with a durable aluminum chassis and powerful performance for everyday computing tasks.",
    price: 999,
  },
  {
    id: 30,
    title: "LG Gram 16",
    category: "Laptop",
    brand: "LG",
    image: "https://via.placeholder.com/150",
    description: "LG Gram 16 offers a lightweight and durable design with long-lasting battery life, perfect for productivity on the go.",
    price: 999,
  },
]
